name: React Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: |
        cd src/frontend
        npm ci || npm install
    - name: Run linter
      run: |
        cd src/frontend
        npm run lint || echo "Linting skipped due to missing configuration"
      continue-on-error: true
    - name: Test
      run: |
        cd src/frontend
        npm test -- --watchAll=false --passWithNoTests
